---

   - name: Install Nginx letsencrypt
     hosts: reversproxy
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - nginx
       - nodeexporter
       - proxy

   - name: Install dbase 
     hosts: db01 db02
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - nodeexporter
       - mysql


   - name: Install wordpress
     hosts: app
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - nodeexporter
       - wordpress


   - name: Install gitlab
     gather_facts: true
     hosts: gitlab
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - ansible-role-gitlab
       - nodeexporter

   - name: Install runner
     hosts: runner
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - nodeexporter
       - runner


   - name: Install monitoring
     hosts: monitoring
     become_method: sudo
     become: true
     become_user: root
     remote_user: konstantin
     roles:
       - walkinghosts
       - nodeexporter
       - monitoring
       - grafana



